name: Security Audit

on:
  pull_request:
    paths:
      - '**/Cargo.lock'
      - '**/Cargo.toml'
  push:
    branches: [main]
  schedule:
    # Run daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  audit:
    name: Cargo Audit
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: pipeline-kit-rs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo-audit
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/cargo-audit
          key: ${{ runner.os }}-cargo-audit-${{ hashFiles('~/.cargo/bin/cargo-audit') }}

      - name: Install cargo-audit
        run: cargo install cargo-audit --locked || true

      - name: Run security audit
        run: cargo audit --deny warnings

      - name: Check for yanked crates
        run: cargo audit --deny yanked

      - name: Security report summary
        if: always()
        run: |
          echo "### 🔒 Security Audit Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          cargo audit 2>&1 | tee -a $GITHUB_STEP_SUMMARY || true
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Checked against [RustSec Advisory Database](https://rustsec.org/)" >> $GITHUB_STEP_SUMMARY

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
          deny-licenses: GPL-3.0, AGPL-3.0
          comment-summary-in-pr: always
